### ISSUE TITLE
complete social side pages

### ISSUE THREAD

**Issue by qauchida** [radgrad/CSExplore-Quinne#12]
- [ ] News Feed Page #6 
- [ ] Fixed Donations Page #7 
- [ ] Game Stats Page #8 
- [ ] Project Page #9 
- [ ] User Settings Page #10 
- [ ] Customizable User Page #11
