### ISSUE TITLE
Complete Game Side Pages

### ISSUE THREAD

**Issue by qauchida** [radgrad/CSExplore-Quinne#5]
- [x] issue #2: Exchange Page
- [x] issue #3: Activities Page
- [x] issue #4: Player's Ahupua'a Page
